### ISSUE TITLE
[功能完善]搜索框组件下拉框不会自动隐藏

### ISSUE THREAD

**Issue by anyshift** [readpage/undraw-ui#11]
目前还没有看到有相关方法暴露出用于手动关闭下拉框：

![pic](https://i.drop.cm/18909076989f08ac6e9eb36df.png)

**Comment by readpage** [comment]
<template>
  <u-search :config="config" style="margin-left: 20px" @submit="submit" ref="searchRef"></u-search>
  <div>abdds</div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { SearchConfig, SearchInstance } from 'undraw-ui'

defineOptions({
  name: 'search'
})

const searchRef = ref<SearchInstance>()

const config = reactive<SearchConfig>({
  keywords: [],
  hotSearchList: []
})

onMounted(() => {
  setTimeout(() => {
    config.keywords = ['斗罗大陆', '斗破苍穹', '吞噬星空', '凡人修仙传', '一念永恒'] // 搜索框关键字滚动
    config.hotSearchList = [
      '斗罗大陆',
      '斗破苍穹',
      '吞噬星空',
      '凡人修仙传',
      '一念永恒',
      '完美世界',
      '鬼灭之刃',
      '间谍过家家',
      '武动乾坤',
      '神印王座'
    ] // top10 热门搜索 最多显示10条数据
  }, 200)
})
const submit = (val: string) => {
  console.log(val)
  searchRef.value?.close()
  // window.open('/all?keyword=' + val)
}
</script>

<style lang="scss" scoped></style>
