### ISSUE TITLE
评论组件工具栏根据变量决定是否显示

### ISSUE THREAD

**Issue by ANCB520** [readpage/undraw-ui#12]
在一些情况下,工具栏中的菜单显示需要根据当前评论的一些状态来决定是否显示,比如对评论进行加精后,工具栏中的菜单需要改变为取消加精等
感觉这个功能应该还是比较有必要的,相应的使用场景比较多,建议可以增加

**Comment by f1dao** [comment]
```
export interface UserApi {
  id: string | number
  username: string
  avatar: string
  likeIds: string[] | number[]
  admin?: boolean
}
```

我在User对象加一个可选admin, true是管理员;
// 默认全部用户显示，#user当前用户显示，#other当前用户以外显示, #具有admin管理员账户全部用户显示
  tools: ['举报#other', '删除#user,admin', '复制', '屏蔽#other']

你看下这样使用可以不!或者你用更好的建议！

**Comment by ANCB520** [comment]
或许可以给单个评论也允许配置菜单选项?

**Comment by ANCB520** [comment]
比较简单的就是直接给显示工具栏的菜单附加一个点击事件,将当前评论信息传递出来,用户根据自己的需要来动态修改工具栏内容

**Comment by f1dao** [comment]
> 比较简单的就是直接给显示工具栏的菜单附加一个点击事件,将当前评论信息传递出来,用户根据自己的需要来动态修改工具栏内容

ok,点击事件方法我会加一个Comment对象传递过来。

**Comment by f1dao** [comment]
> 或许可以给单个评论也允许配置菜单选项?

具体点不清楚!

**Comment by ANCB520** [comment]
> > 或者许可以给单个评论也允许配菜单选项？
> 
> 具体点不清楚！

就是给每个评论都加一个配置选项,可以在其中单独为每一个评论进行配置设置,配置中就包括了单个评论的工具栏配置

**Comment by f1dao** [comment]
> 比较简单的就是直接给显示工具栏的菜单附加一个点击事件,将当前评论信息传递出来,用户根据自己的需要来动态修改工具栏内容

![image](https://github.com/readpage/undraw-ui/assets/114089389/b3332c73-10c2-42f4-8c66-97867af9e125)
有评论信息传递过来的

**Comment by f1dao** [comment]
> 每个评论都加一个配置选项

每个评论都加一个配置选项，不好实现，只能实现统一和分类的。

**Comment by f1dao** [comment]
> 或许可以给单个评论也允许配置菜单选项?

请具一个网站例子

**Comment by ANCB520** [comment]
> > 或许可以给单个评论也允许配置菜单选项?
> 
> 请举一个网站例子

就像点赞一样,如果把点赞放到工具栏中,那么第一次显示的是点赞,点赞完成后再次点击这个评论的工具栏打开就应该是取消点赞,

**Comment by readpage** [comment]
@ANCB520 工具栏重构，改成可自定义卡槽！

**Comment by readpage** [comment]
> @ANCB520 ok, 工具栏重构，改成可自定义卡槽！

**Comment by readpage** [comment]
@ANCB520 
![image](https://github.com/readpage/undraw-ui/assets/65387014/82440a9f-f37d-4567-901b-5dcbb6506490)

> 卡槽实现例子,卡槽不支持事件，你可以通过卡槽传递的参数comment对象处理

`
<template #operate="scope">
  <Operate comment="scope"></Operate>
</template>
`

**Comment by readpage** [comment]
> @ANCB520 ![image](https://user-images.githubusercontent.com/65387014/237355407-82440a9f-f37d-4567-901b-5dcbb6506490.png)
> 
> > 卡槽实现例子,卡槽不支持事件，你可以通过卡槽传递的参数comment对象处理
> 
> `<template #operate="scope"> <Operate comment="scope"></Operate> </template>`
是否赞同这个方法，赞同我就重构操作栏！

**Comment by ANCB520** [comment]
> > @ANCB520 ![image](https://user-images.githubusercontent.com/65387014/237355407-82440a9f-f37d-4567-901b-5dcbb6506490.png)
> > > 卡槽实现例子,卡槽不支持事件，你可以通过卡槽传递的参数comment对象处理
> > 
> > 
> > `<template #operate="scope"> <Operate comment="scope"></Operate> </template>`
> > 是否赞同这个方法，赞同我就重构操作栏！

抱歉,才看到,对此我没有意见

**Comment by ANCB520** [comment]
这是我的临时解决办法
`
const handleListClick=(e) =>{
    const clickedItem = e.target.closest('.operation-warp');
    if (clickedItem) {
      if (clickedItem.classList.contains('operation-warp')) {
        const commentList = clickedItem.closest('.comment-list');
        const commentItems = commentList.querySelectorAll('.comment');
        const replyList = clickedItem.closest('.reply-list');
        let replyIndex=-1;
        let commentIndex=-1;
        if (replyList) {
          const reply = clickedItem.closest('.reply');
          const replyItems = replyList.querySelectorAll('.reply');
          replyIndex = Array.prototype.indexOf.call(replyItems, reply);
          const comment = replyList.closest('.comment');
          commentIndex = Array.prototype.indexOf.call(commentItems, comment);
        } else {
          const comment = clickedItem.closest('.comment');
          commentIndex = Array.prototype.indexOf.call(commentItems, comment);
        }
        
        let commentContent;
        if(commentIndex>-1){
          if(replyIndex>-1){
            commentContent=config.comments[commentIndex].reply.list[replyIndex];
          }else{
            commentContent=config.comments[commentIndex];
          }
          console.log("点击工具栏对应的评论",commentContent)
        }
          
      }
    }
  }`

**Comment by ANCB520** [comment]
![image](https://github.com/readpage/undraw-ui/assets/23068266/60e04c53-2132-4d57-9042-3962865d10c6)
如果可以,希望工具栏在没有内容的时候能够隐藏
