### ISSUE TITLE
有没有评论权限设置功能

### ISSUE THREAD

**Issue by abusizhishen** [readpage/undraw-ui#17]
没找到，如果没有的话有没有在计划之中，我的场景是用户登录之后才能评论，需要在评论时检查权限，或者在初始化时根据权限配置是否显示评论框

**Comment by abusizhishen** [comment]
> 你先临时在评论提交事件submit做拦截处理，弹出登录窗口或者警告提示，下一个版本新增一个评论框焦点事件，你可以加一些事务比如弹出登录框或者弹出一个警告提示框是否确定登录，确定跳转跳转登录页面。你觉得可以就增加评论框焦点事件功能！

好的，不只是评论框，还有下面的评论点赞，对评论再回复也需要

**Comment by readpage** [comment]
有点赞事件的，你写一个拦截方法加入点赞事件和下一个版本的评论框焦点事件就行！

**Comment by readpage** [comment]
不执行finish()方法就不会改变数据

**Comment by readpage** [comment]
https://github.com/readpage/undraw-ui/commit/0598e523103caeaf870e647c20ce83a152fe6bd4
