### ISSUE TITLE
关于评论置顶功能

### ISSUE THREAD

**Issue by xiaxichen** [readpage/undraw-ui#23]
请问有增加评论置顶功能的想法吗？

**Comment by readpage** [comment]
指定功能你可以在自定义工具栏加置顶按钮实现，你可以在评论对象加一个置顶属性，后端根据判断排序，置顶评论显示你可以在用户信息卡槽自定义

**Comment by xiaxichen** [comment]
> 置顶功能你可以在自定义工具栏加置顶按钮实现，你可以在评论对象加一个置顶属性，后端根据判断排序，置顶评论显示你可以在用户信息卡槽自定义

了解了 请问下评论分页是哪个属性控制的呢？我在文档中没有看懂关于分页设置的参数只看到了一个评论回复的分页。
