### ISSUE TITLE
关于评论置顶排序修改后如何在时间前显示该评论为置顶评论

### ISSUE THREAD

**Issue by xiaxichen** [readpage/undraw-ui#24]
关于评论置顶排序修改后如何在时间前显示该评论为置顶评论
我这边使用工具栏完成了置顶功能，但是现在我想在评论标识上显示该评论为置顶评论，请问我如何实现呢？

**Comment by readpage** [comment]
你可以再submit事件追加到content前面，如图片上一样。内容显示支持html+css语法






draw
***@***.***

15885326304


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "readpage/undraw-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 下午4:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[readpage/undraw-ui] 关于评论置顶排序修改后如何在时间前显示该评论为置顶评论 (Issue #24)





 
关于评论置顶排序修改后如何在时间前显示该评论为置顶评论
 我这边使用工具栏完成了置顶功能，但是现在我想在评论标识上显示该评论为置顶评论，请问我如何实现呢？
