### ISSUE TITLE
用户信息卡片，关注未关注显示切换

### ISSUE THREAD

**Issue by kcaco2000** [readpage/undraw-ui#26]
![image](https://github.com/readpage/undraw-ui/assets/42790380/e05ccc81-fdbf-4e3a-8bae-bb45147221dc)

scope能否添加类似isFollow字段来标识是否已关注该用户？

或者有其他什么好的办法来解决是否关注按钮显示状态？

**Comment by readpage** [comment]
showInfo事件为scope传值

**Comment by readpage** [comment]
finish传递回调值，对象可以自定义

**Comment by kcaco2000** [comment]
好的 感谢
