### ISSUE TITLE
多级回复问题

### ISSUE THREAD

**Issue by luoxiaobai-1** [readpage/undraw-ui#27]
如果要体现多级回复，后端返回数据结构应该是什么？

**Comment by readpage** [comment]
parentId 根节点 最高层&nbsp;replyId 为父节点 回复id
可以参考数据库Java/docs/sql/undraw.sql · undraw/undraw-comment-demo - 码云 - 开源中国 (gitee.com)
&nbsp;


draw
***@***.***

15885326304


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr. ***@***.***&gt;; 
发送时间: 2024年3月10日(星期天) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [readpage/undraw-ui] 多级回复问题 (Issue #27)





 
如果要体现多级回复，后端返回数据结构应该是什么？
