### ISSUE TITLE
HelloGitHub 徽章计划

### ISSUE THREAD

**Issue by 521xueweihan** [readpage/undraw-ui#29]
🎉 恭喜！您的[项目](https://hellogithub.com/repository/787564b16f214b2f851724bc140cb493)已被 HelloGitHub 社区收录和推荐，现邀请您加入 HelloGitHub 徽章计划。加入后，您将获得以下特权：

- 社区认可: 徽章代表你的项目已通过 HelloGitHub 社区的严格筛选，并获得推荐。
- 提高曝光: 佩戴徽章后，你的项目将获得更多推荐流量，吸引更多用户和贡献者。
- 增强互动: 用户可通过徽章快速了解项目，并与之互动（点赞、评论、收藏）。
- 收集反馈: 获取广大用户的真实反馈，持续优化你的项目。
- 特殊标识: 认证后，你的评论将有显著标识，并获得置顶优先权。

📌 [立即点击](https://hellogithub.com/repository/787564b16f214b2f851724bc140cb493/embed) 完成徽章佩戴，加入 HelloGitHub 徽章计划，让你的开源项目绽放更耀眼的光彩。

---

**HelloGitHub**，一个专注于发现、分享、推广开源项目的社区。自 2016 年创立以来，从每月一更的月刊发展到今天，已经成为一个拥有超过 **1 万** 用户的充满活力的开源社区。我们的足迹遍布多个内容平台，并获得了全网 **50 万** 粉丝的信赖与支持。

<img width="1245" alt="截屏2024-06-12 09 29 42" src="https://github.com/No-Chicken/OV-Watch/assets/8255800/7ac6b71e-f052-4f44-88b1-5c772e917348">

**Comment by 521xueweihan** [comment]
@readpage 兄弟怎么自己悄悄佩戴了，也没提交认领状态，也不和我说一声，太不拿我当自己人了。

佩戴上徽章后点击「提交」，我好给你全站置顶再推一波。另外小徽章也上线了，可自行选择佩戴的样式哈。

<img width="693" alt="截屏2024-07-04 16 00 22" src="https://github.com/readpage/undraw-ui/assets/8255800/54e7e754-1f0b-4668-98f0-a4337a12dbb2">

**Comment by readpage** [comment]
不好意思，我看你发流程点击佩戴徽章就没了。

**Comment by 521xueweihan** [comment]
@readpage 您这属于做好事不留名了😂

我这边已经通过啦。因为网站只能置顶 3 个项目，我明天会全站置顶 undraw-ui 项目（1 天），到时候再来通知您。

<img width="770" alt="image" src="https://github.com/readpage/undraw-ui/assets/8255800/05b8f962-3a80-4a68-a565-acc721e6e7c3">

再次感谢您的支持。

**Comment by 521xueweihan** [comment]
已置顶
<img width="1063" alt="image" src="https://github.com/readpage/undraw-ui/assets/8255800/fc8a2c7d-d6dc-4f96-9e4b-bebe88a3f275">
