### ISSUE TITLE
评论组件问题

### ISSUE THREAD

**Issue by zhangming-chinasoftinc** [readpage/undraw-ui#30]
把评论组件放到element-plus的抽屉组件内时，表情会选择不了
![image](https://github.com/readpage/undraw-ui/assets/141893215/38c29958-4ca8-4d16-96d1-abbeced6a1bc)

**Comment by readpage** [comment]
能提供一个demo实例吗?

**Comment by readpage** [comment]
控制台查看抽屉组件和表情包组件样式z-index优先级。把表情包z-index调高或者抽屉组件z-index调低。修改css 的z-index数值

**Comment by readpage** [comment]
css样式可以自行根据浏览器控制台调整，js部分在做修复和增强处理。

**Comment by zhangming-chinasoftinc** [comment]
我还遇到一个BUG，就是选择表情的时候，如果输入框内没有内容就选不了表情，输入框内有内容才可以

**Comment by readpage** [comment]
使用的是多少版本，更新到最新按需引入。
&nbsp;


draw
***@***.***

15885326304


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月4日(星期四) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [readpage/undraw-ui] 评论组件问题 (Issue #30)














 
我还遇到一个BUG，就是选择表情的时候，如果输入框内没有内容就选不了表情，输入框内有内容才可以

**Comment by zhangming-chinasoftinc** [comment]
使用的是1.1.1的版本，引入的话，由于我是只使用到了评论，我是自定义导入的
![image](https://github.com/readpage/undraw-ui/assets/141893215/2e5b4dce-a830-4a4d-bdce-b87ed7d3f3c3)

**Comment by readpage** [comment]
你提供一个实例仓库，我才能定位到问题点。

**Comment by zhangming-chinasoftinc** [comment]
我提供一下我封装的代码，你帮忙看看
这是版本信息
![image](https://github.com/readpage/undraw-ui/assets/141893215/2e7a5ac6-f3b0-44ef-8f25-33f6585f4425)
[comment.zip](https://github.com/user-attachments/files/16092783/comment.zip)
这是组件代码

**Comment by readpage** [comment]
我没有出现上述问题，你还是提供一个完整demo吧！

**Comment by zhangming-chinasoftinc** [comment]
可以把评论组件内的 ElImage 预览加上 preview-teleported 属性么？现在预览有点问题
![Uploading image.png…]()

**Comment by readpage** [comment]
图片没有上传成功 ，ok！是上传图片后显示评论列表内容图片吗

**Comment by readpage** [comment]
> 我还遇到一个BUG，就是选择表情的时候，如果输入框内没有内容就选不了表情，输入框内有内容才可以

使用element-plus2.1.6以上
