### ISSUE TITLE
用户等级设置显示不显示  默认不显示

### ISSUE THREAD

**Issue by yangxun521** [readpage/undraw-ui#5]
`const grade = (v: number) => {
  switch (v) {
    case 1:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="831">...</svg>'
    case 2:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="765">...</svg>'
    case 3:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="799">...</svg>'
    case 4:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="815">...</svg>'
    case 5:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="782">...</svg>'
    default:
      return '<svg viewBox="0 0 1682 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="748">...</svg>'
  }
}`

default 可以设置无  就是不显示

**Comment by readpage** [comment]
Resolves user levels.
