### ISSUE TITLE
点击用户昵称跳转用户详情

### ISSUE THREAD

**Issue by yangxun521** [readpage/undraw-ui#6]
`<div class="user-box">
        <a href="/user/1556564194374926" target="_blank" rel="" class="username">
          <span class="name" style="max-width: 10em">{{ data.username }}</span>
          <span blank="true" class="rank">
            <u-icon size="24" v-html="grade(data.grade)"></u-icon>
          </span>
        </a>
        
        <time class="time">{{ data.createTime }}</time>
      </div>`
这里用a标签不太好  用router-link吧  如果兼容各种情况  还是点击事件最靠谱

**Comment by readpage** [comment]
在user对象里加url字符串地址如何?
@yangxun521 
![image](https://user-images.githubusercontent.com/65387014/169429728-6ded0812-63ec-4b23-b72b-3c009d8f86dd.png)

**Comment by readpage** [comment]
用router-link吧
-- 回复
没有引入vue-router工具包
只能用a标签

**Comment by yangxun521** [comment]
用点击事件也行  跳不跳转  开发者可以根据需求变化 大佬觉得如何

**Comment by readpage** [comment]
> 用点击事件也行跳不跳转 开发者可以根据需求变化 大佬觉得如何

怎么说呢，尽量减少事件请求后端，用户评论后根据id查询数据获取用户信息,存储在评论表里，当再次获取评论列表减少了再次通过id获取用户信息。所以我觉得尽量把需要的用户数据放在评论这个对象里。

用户评论我先在评论属性加detailUrl字段作为条件链接地址，先看下效果，如果实在不行后面可能会有变动。

---- From commit [2e47b4c](https://github.com/readpage/undraw-ui/commit/2e47b4cdfb85f325d002ac8050d4b687e9b645a5)

**Comment by readpage** [comment]
后面加些卡槽<slot>,灵活、自由性点！

**Comment by yangxun521** [comment]
与后端无关吧  点击事件 无非也是把该用户id传过来  跳转用户详情  router.push("/user/1")  /user/:id  a标签 在vue项目里面用不太好吧

**Comment by readpage** [comment]
好的！22号考试了，等23号后我在修改！如果你急着用的话，有思路你PR下合并(最好会git命令)，我可以发布新版本！

**Comment by readpage** [comment]
To release version 0.5.1

23号之前不在更新!
