### ISSUE TITLE
我按照文档中的代码复制带自己的项目上怎么显示不了呢

### ISSUE THREAD

**Issue by l406054531** [readpage/undraw-ui#7]
TypeError: Failed to fetch
    at showOriginal.js:15:5
    at twpConfig.onReady (config.js:65:17)
    at showOriginal.js:5:11

控制台报的错

**Comment by readpage** [comment]
拉取这个项目，参考这个实例
https://gitee.com/undraw/undraw-ui-demo

**Comment by readpage** [comment]
vue3 版本必须大于vue@"^3.2.25
